# Generated by Django 4.2.3 on 2023-08-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='slug',
            field=models.SlugField(default='', max_length=250, unique=True),
        ),
    ]
