# Generated by Django 4.2.3 on 2023-08-07 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_manufacturer_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['name']},
        ),
    ]
