# Generated by Django 4.2.3 on 2023-08-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_review_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
